Add release GitHub actions
drivendataorg/cookiecutter-data-science pull request #336
Opened 2023-12-01 22:00 UTC by klwetstone

closes [#317](https://github.com/drivendata/cookiecutter-data-science/issues/317)

Add GitHub actions to publish on release

**Do not merge** - [#315](https://github.com/drivendata/cookiecutter-data-science/issues/315) is needed first. After transfer, the repo should automatically have access to the PyPI secrets needed by `release.yml`

#### `ccds.__version__`

Users can now see the version of `ccds` after importing (`ccds.__version__`). However, the *project* name is different than the *module* name. This means that in `version.py`, we have to hard code the project name with:

```python
__version__ = importlib_metadata.version("cookiecutter-data-science")
```

Instead of using:

```python
__version__ = importlib_metadata.version(__name__.split(".", 1)[0])
```

2024-08-12 17:36 UTC, pjbull commented on ccds/__main__.py
> +        f.params[4].default = __version__
I feel like first param being the repo is unlikely to change, but I am a little worried about ones later in the ordering. Is there a way we can loop over parameters and check by name to find the right one?

2025-01-03 15:34 UTC, chrisjkuch commented on ccds/__main__.py
> +        f.params[4].default = __version__
This is updated to find the "checkout" option by name in the list of cookiecutter parameters.

2025-01-03 17:41 UTC, jayqi commented on docs/docs/all-options.md
> +By default, `ccds` will download the most recently _released_ version of the template. If there are any _unreleased_ changes to the template (or changes in a separate branch) that you want to incorpo
Is this still accurate? This seems like it defaults to match the current version of `ccds` that is installed.

2025-01-03 17:45 UTC, chrisjkuch commented on docs/docs/all-options.md
> +By default, `ccds` will download the most recently _released_ version of the template. If there are any _unreleased_ changes to the template (or changes in a separate branch) that you want to incorpo
Good catch, it's not, I'll update.

2025-01-28 18:00 UTC, pjbull reviewed
Great! Looking good with one question.

May be nice to also add some instructions on creating a release for maintainers so they know to tag the release in the right way.

2025-01-28 18:00 UTC, pjbull commented on ccds/__main__.py
> +        f.params[checkout_index].default = __version__
It looks like some places (like the release tags), we use `vX.Y.Z` and others we use `X.Y.Z`. We should check if we need the `v` prefix here or not.

2025-02-07 12:19 UTC, chrisjkuch commented on ccds/__main__.py
> +        f.params[checkout_index].default = __version__
@pjbull great catch, would have failed as-is without the "v" prefix. I added a `RELEASING.md` with some instructions, but feel free to tweak or make suggestions.

2025-02-07 15:32 UTC, r-b-g-b requested changes
Really nice! A couple of wording tweaks using my status as "kind of still figuring out what's going" on to write what made it click for me.

Also maybe unrelated but I notice that

```bash
ccds --version

## Cookiecutter 2.6.0 from /home/robert/projects/codepath-data-infrastructure/.venv/lib/python3.13/site-packages (Python 3.13.1 (main, Dec 19 2024, 14:32:25) [Clang 18.1.8 ])
```

Outputs the `cookiecutter` version (2.6.0), not the `ccds` version (2.0.1). May be inert for the time being and if so I can file an issue for another day.

2025-02-07 15:32 UTC, r-b-g-b commented on README.md
> +By default, `ccds` will use the version of the template that corresponds to the installed version (e.g., if you have installed version v2.0.1, you'll use the v2.0.1 version of the template by default
```suggestion
By default, `ccds` will use the _project template_ version that corresponds to the _installed `ccds` package_ version (e.g., if you have installed `ccds` v2.0.1, you'll use the v2.0.1 version of the project template by default). To use a specific version of the project template, use the `-c/--checkout` flag to provide the branch (or tag or commit hash) of the version you'd like to use. For example to use the project template from the `master` branch:
```

Seems to be referred to as "project template" elsewhere (easier for me to comprehend in any case).

2025-02-07 15:32 UTC, r-b-g-b commented on RELEASING.md
> +The release of [ccds v2](https://drivendata.co/blog/ccds-v2) introduced the `ccds` utility and the concept of versioning to cookiecutter data science. Prior to this release, there was just the templa
```suggestion
The release of [ccds v2](https://drivendata.co/blog/ccds-v2) introduced the `ccds` utility and the concept of versioning to cookiecutter data science. Prior to this release, cookiecutter-data-science only provided a project template, which the generic [cookiecutter](https://github.com/cookiecutter/cookiecutter) utility could use to instantiate a project.  Branches and forks could be used in the usual way to get different versions of the template.
```

Slight rewording -- still accurate?

2025-02-07 16:41 UTC, chrisjkuch commented on RELEASING.md
> +The release of [ccds v2](https://drivendata.co/blog/ccds-v2) introduced the `ccds` utility and the concept of versioning to cookiecutter data science. Prior to this release, there was just the templa
yeah this is much more clear

2025-02-14 13:15 UTC, chrisjkuch commented
@r-b-g-b could you take one more look here? Applied your suggestions and added a warning about v2.0.0 per @pjbull, who has otherwise signed off

2025-02-14 14:22 UTC, r-b-g-b approved these changes
One minor tweak, then good to merge -- great work!

2025-02-14 14:22 UTC, r-b-g-b commented on hooks/pre_prompt.py
> +        )
[nit] my brain found it easier to reason about < 2.0.1 than <= 2.0.0 ("if the version is less than 2.0.1, show the deprecation warning")

Then tweaked the wording a bit -- still correct?

```suggestion
    if version < "2.0.1":
        warnings.warn(
            "It looks like you're using a version of CCDS that "
            "defaults to using the latest template. For more stable behavior, "
            "update to CCDS version 2.0.1 or later.",
            DeprecationWarning,
        )
```

2025-02-14 19:54 UTC, pjbull commented on hooks/pre_prompt.py
> +        )
Would be good to tell people how to upgrade (e.g., `pip install -U cookiecutter-data-science`)

2025-02-14 19:56 UTC, r-b-g-b commented on hooks/pre_prompt.py
> +        )
Good call -- updated suggestion.

2025-02-15 21:50 UTC, pjbull commented on hooks/pre_prompt.py
> +            "version, run 'pip install -U cookiecutter-data-science'",
I might say "Upgrade to the latest with your package manager, for example `pip install -U cookiecutter-data-science`."

2025-02-16 17:34 UTC, pjbull approved these changes

2025-02-16 18:45 UTC, merged