Added support for the uv package and project manager
drivendataorg/cookiecutter-data-science pull request #408
Opened 2024-12-29 05:42 UTC by GatlenCulp

[uv](https://docs.astral.sh/uv/) is an extremely fast Python package and project manager, written in Rust by the same folk who created the ruff package manager.

Implementing this support was as simple as updating the Makefile, adding a harness, and adding it as an option to ccds.

The tests for uv as an additional environment manager were added and are passing.

2025-03-01 04:20 UTC, jayqi requested changes

2025-03-01 04:20 UTC, jayqi commented on {{ cookiecutter.repo_name }}/Makefile
> +	uv pip install pip
I don't think we need to install pip if uv is being chosen as the environment manager.

2025-03-01 04:20 UTC, jayqi commented on pyproject.toml
> +addopts = "-vv --color=yes"
As a general code style thing, can you make sure all files end in a newline?

2025-03-01 04:20 UTC, jayqi commented on tests/virtualenv_harness.sh
> +run_tests $PROJECT_NAME $MODULE_NAME
Per other comment about having files end in a newline, this file shouldn't have any changes.

2025-03-04 10:59 UTC, chrisjkuch commented on tests/virtualenv_harness.sh
> +run_tests $PROJECT_NAME $MODULE_NAME
@jayqi the file on master has two newlines at the end of it, so technically this change is making the file correctly formatted. Can move this change to a separate formatting PR though if desired.

2025-03-04 22:10 UTC, jayqi approved these changes
Looks good to me.

As a note: When we write the changelog entry for this, we should say that we've added support for the `uv pip` interface. 

We don't support the uv project interface yet, which @GatlenCulp mentioned in the PR description. This requires support for pyproject.toml (new issue #431). We may want to use PEP 735 dependency groups. It'll make sense to work on that in the near future—even regular Pip will be releasing support for them in their April release.

2025-03-05 17:11 UTC, merged