Add PyTest IDs for better readability and filtering
drivendataorg/cookiecutter-data-science pull request #409
Opened 2024-12-30 22:37 UTC by GatlenCulp

2025-01-08 17:14 UTC, chrisjkuch commented
Sorry for the delay on this @GatlenCulp - would you mind fixing the linting issue so I can run the tests?

2025-02-16 14:47 UTC, chrisjkuch commented on tests/conftest.py
> +
```suggestion

```

2025-02-16 14:51 UTC, chrisjkuch commented on tests/conftest.py
> +        return f"{config['environment_manager']}-{config['dependency_file']}-{config['docs']}"
```suggestion
        return f"{config['environment_manager']}-{config['dependency_file']}-{config['docs']}"

```

2025-02-27 10:49 UTC, chrisjkuch requested changes
One small comment, then looking for another reviewer and we should be good to go!

2025-02-27 10:49 UTC, chrisjkuch commented on tests/conftest.py
> +        return f"{config['environment_manager']}-{config['dependency_file']}-{config['docs']}"
I think this would be more informative if we named the config with whether it contained the basic pydata packages rather than docs, since the former has more impact than the latter.
```suggestion
        return f"{config['environment_manager']}-{config['dependency_file']}-{config['pydata_packages']}"
```

2025-03-04 13:55 UTC, chrisjkuch approved these changes
Thanks again for the PR - I've made a few slight tweaks and now looks good to me! Will get another reviewer to check my work, then we're planning to merge for a 2.0.2 release with #387 and #408

2025-03-04 22:19 UTC, jayqi approved these changes
LGTM

2025-03-05 15:42 UTC, merged